# permissions for end users to view harpoons.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: harpoon-viewer-role
rules:
- apiGroups:
  - harpoon.containers
  resources:
  - harpoons
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - harpoon.containers
  resources:
  - harpoons/status
  verbs:
  - get
