# permissions for end users to edit harpoons.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: harpoon-editor-role
rules:
- apiGroups:
  - harpoon.containers
  resources:
  - harpoons
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - harpoon.containers
  resources:
  - harpoons/status
  verbs:
  - get
